### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by marcoconti83** [wireapp/wire-ios-data-model#87]
![screen shot 2016-11-24 at 11 19 22](https://cloud.githubusercontent.com/assets/620000/20595080/ddb0bb92-b238-11e6-8ec8-bd4cab400240.png)
![screen shot 2016-11-24 at 11 19 26](https://cloud.githubusercontent.com/assets/620000/20595084/df31cc2c-b238-11e6-9ce8-c225cc78416f.png)
![screen shot 2016-11-24 at 11 23 01](https://cloud.githubusercontent.com/assets/620000/20595088/e06e5fce-b238-11e6-9961-e12061716803.png)

**Comment by marcoconti83** [comment]
![screen shot 2016-11-24 at 11 31 59](https://cloud.githubusercontent.com/assets/620000/20595284/a4f44f70-b239-11e6-9794-80a9c1dcc620.png)

**Comment by mikeger** [comment]
![screen shot 2018-03-12 at 11 11 18](https://user-images.githubusercontent.com/715129/37278143-11c4f4ca-25e7-11e8-887d-a378a320f0cc.png)
![screen shot 2018-03-12 at 10 55 13](https://user-images.githubusercontent.com/715129/37278150-158ad340-25e7-11e8-86d2-9f11a0d1a8dc.png)
